# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "acc40522f794345381a50400eae6e868"
application_url = "https://moves-animal-critical-accepted.trycloudflare.com"
embedded = true
name = "ethical-supply-app"
handle = "ethical-supply-app-6"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "app/uninstalled" ]
  uri = "/shopify/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://moves-animal-critical-accepted.trycloudflare.com/auth/callback",
  "https://moves-animal-critical-accepted.trycloudflare.com/auth/shopify/callback",
  "https://moves-animal-critical-accepted.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
